# The license for this mod.
license="${mod_license}"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://furranystudio.fr" #optional
iconFile="assets/avalinexus/img/AN-Icon.png" #optional
#bannerFile="assets/avalinexus/img/AN-Banner.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[${geckolib_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    type="required"
    versionRange="[${terrablender_version},)"
    ordering="NONE"
    side="BOTH"
