org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=26.3
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[26.3,27)
# The NeoForge version must agree with the Minecraft version to get a valid artifact
neo_version=26.3.0.23-beta
# GeckoLib (models and animations) - https://github.com/bernie-g/geckolib
geckolib_version=5.5.7
# TerraBlender (biome regions) - https://github.com/Glitchfiend/TerraBlender
terrablender_version=26.3.0.0.7

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=avalinexus
# The human-readable display name for the mod.
mod_name=Avali Nexus
# The license of the mod. Review your options at https://choosealicense.com/.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.0.0
# The group ID for the mod.
mod_group_id=org.furranystudio
# The authors of the mod.
mod_authors=Maxime66410
# The description of the mod.
mod_description=Avali Nexus introduces the nomadic Avali species to Minecraft. Explore their unique biome, discover high-tech villages, encounter new creatures, and unlock futuristic survival gear.
